hpe-storage/common-host-libs

windows/iscsidsc/add_iscsi_send_target_portal.go
windows/iscsidsc/get_iscsi_session_list.go
windows/iscsidsc/iscsidsc.go
windows/iscsidsc/login_iscsi_target.go

* Problem:
* Need to add iSCSI discovery API support to add a send target portal
* Need to fix a few minor issues
* NOTE:  Entry/exit logging still using Info vs Trace; will resolve in all packages in a future update
* add_iscsi_send_target_portal.go
* New file that wraps the AddIScsiSendTargetPortalW() iSCSI API
* get_iscsi_session_list.go
* When no sessions are connected, the iSCSI API would still return ERROR_INSUFFICIENT_BUFFER with a sessionCount of 0.  To make sure we get a clean non-failing call to this API, we've added a check for bufferSizeNeeded > 0.  That way if the API indicates it wants a larger buffer, we'll allocate the buffer and then call the API a second time.
* iscsidsc.go
* Added definitions for iSCSI API ISCSI_ALL_INITIATOR_PORTS and …

chapi2: Cleanup/Extend Windows iSCSI API support

---

chapi2/multipath/multipath_util.go
chapi2/multipath/multipath_util_test.go

* Problem:
* Target type cache test package was failing
* No defect was found in the actual cache code
* Test package was using very short timeouts to try and exercise all of the cache capabilities
* Moved log.Info* to log.Trace* so that output does not appear in the console output when "go test" is executed
* Reduced the maximum cache count from 512 to 32 to speed up performance
* Testing:
* Ran "go test" on local host for 25+ iterations without failure
* Reviewers:
* @shivamerla @rgcostea 
* Bug: N/A

chapi2:  Fix target type cache test failures

---

chapi2/iscsi/iscsi.go
chapi2/iscsi/iscsi_linux.go
chapi2/iscsi/iscsi_windows.go
chapi2/model/types.go
chapi2/model/types_linux.go
chapi2/model/types_windows.go
chapi2/multipath/multipath_windows.go
windows/iscsidsc/add_iscsi_send_target_portal.go

* Problem:
* Enhance CHAPI2 iSCSI package
* chapi2 model package
* Added const strings for AccessProtocolIscsi and AccessProtocolFC.
* Changed IscsiTarget.TargetPortals from an array of TargetPortal objects to an array of pointers to TargetPortal objects.  This makes the usage more consistent with other CHAPI2 objects, such as the Host struct.
* Added a "TargetPortalPrivate" property to the "TargetPortal" object.  This allows for platform specific extensions to the TargetPortal object.
* Defined TargetPortalPrivate object for Windows which contains an iscsidsc.ISCSI_TARGET_PORTAL object.
* Defined an empty TargetPortalPrivate object for Linux.
* chapi2 multipath package
* Changed IscsiTarget.TargetPortals from an array of TargetPortal objects to an array of pointers to …

chapi2: Enhance iSCSI package

---

storageprovider/csp/container_storage_provider.go
storageprovider/csp/container_storage_provider_test.go
storageprovider/fake/fake_storage_provider.go
storageprovider/fake/fake_storage_provider_test.go
storageprovider/storage_provider.go

- Volume clone creation with size >= snapshot size is allowed, else error will be returned.
- CSP handles the resize in CloneVolume() endpoint.

CSI Driver (Clone Volume): Handle clone creation when size greater than source size

---

windows/powershell/disk_cmdlets.go

* Problem:
* InitializeDisk previously only supported GPT partitions
* GPT can only support volumes >= 128 MiB
* Need an option to accept GPT or MBR to the InitializeDisk function
* Define MinimumGPTSize, PartitionStyleMBR, and PartitionStyleGPT constants
* Add "partitionStyle string" as an additional input property
* If "partitionStyle" is an empty string, function will default to GPT
* Testing:
* Tested updated API; able to initialize both MBR and GPT disks
* API is currently not used by other packages (i.e. change will not break anything)
* Future CHAPI2 updates will make use of the extended function to initialize disks
* Reviewers:
* @shivamerla, @suneeth51
* Bug: N/A

powershell:  Add partition style to InitializeDisk function

---

chapi2/chapi_windows.go
chapi2/driver/driver.go
chapi2/fc/fc.go
chapi2/fc/fc_util.go
chapi2/fc/fc_windows.go
chapi2/handler/handler.go
chapi2/handler/handler_windows.go
chapi2/iscsi/iscsi.go
chapi2/iscsi/iscsi_linux.go
chapi2/iscsi/iscsi_windows.go
chapi2/model/types.go
chapi2/mount/mount.go
chapi2/mount/mount_windows.go
chapi2/multipath/multipath.go
chapi2/multipath/multipath_linux.go
chapi2/multipath/multipath_windows.go
windows/iscsidsc/iscsidsc.go
windows/iscsidsc/send_scsi_inquiry.go
windows/powershell/disk_cmdlets.go

* Problem:
* Add DeleteDevice endpoint support for Windows
* Improve logging so that Info and Trace levels are used efficiently
* Across multiple packages, replaced log.Info with log.Trace where applicable
* Replaced entry/exit ">>>" with ">>>>>" logging to be consistent within CHAPI2 and Windows base libraries
* chapi2 types
* Removed "TargetScope" from "Device" object.  It's redundant and already included as an IScsiTarget property (where it belongs)
* Renamed "Partitiontype" with "PartitionType" in "DevicePartition" object (correct CamelCase issue)
* chapi2 driver package
* Added additional Info level logging to provide a high level overview of which endpoints are being called and their return data
* Implemented DeleteDevice() endpoint
* If serial number not present, …

chapi2:  Add DeleteDevice endpoint for Windows plus logging improvements

---

chapi2/chapi.go
chapi2/driver/driver.go
chapi2/handler/handler.go

* Problem:
* CHAPI2 endpoint cleanup
* To align with mounts endpoint, change /api/v1/devices/detail endpoint to /api/v1/devices/details
* In driver.go, align interface parameter definitions with actual implementation
* Minor comment cleanup
* Testing:
* Built successfully for Linux and Windows
* Exercised endpoints under Windows
* Reviewers:
* @shivamerla
* Bug: N/A

chapi2: endpoint cleanup

---

connectivity/client.go
logger/logger.go
util/strings.go

* Problem:
* util.IsSensitive() was returning false positives
* Redundant lookup tables in util.IsSensitive() and logger.Scrubber()
* strings.go
* Remove IsSensitive() function (moved to logger.go)
* logger.go
* Moved IsSensitive() function from strings.go into this module
* Changed lookup table from string array to a map
* Added "accesskey" to lookup table
* Updated Scrubber() routine to use IsSensitive() function
* client.go
* Changed util.IsSensitive() to log.IsSensitive()
* Testing:
* Built successfully for Windows and Linux
* Tested on a Windows host
* Reviewers:
* @shivamerla, @suneeth51, @rgcostea, @vidhutsingh , @raunakkumar 
* Bug: N/A

logger:  Enhance sensitive keyword detection

---

chapi2/chapiclient/chapiclient.go
chapi2/chapiclient/chapiclient_linux.go
chapi2/chapiclient/chapiclient_util.go
chapi2/chapiclient/chapiclient_windows.go
chapi2/handler/handler_windows.go

* Problem:
* Need to port CHAPI1 client package to CHAPI2
* handler_windows.go
* Changed chapiPortFileName to ChapiPortFileName so that string is accessible to other packages (e.g. CHAPI client)
* chapiclient.go
* Ported CHAPI1 code to CHAPI2
* NewChapiClient() and NewChapiClientWithTimeout() are platform independent methods to create a new CHAPI Client object
* **Only** wrap CHAPI2 endpoints in this module
* Simplified all endpoint handlers by wrapping chapiClient.client.DoJSON in a new chapiClient.chapiClientDoJSON() function (shared/common error handling)
* Updated Response object to expect a cerrors.ChapiError object instead of a generic error
* Compilation will fail if Client object does not support CHAPI2's Driver interface (i.e. keep parity between client and …

chapi2: Add chapiclient package

---

chapi2/driver/driver.go
chapi2/host/host_windows.go
chapi2/model/types.go
windows/wmi/wmiquery.go

* Problem:
* Checking in a few miscellaneous CHAPI2 enhancements
* types.go
* After discussions with @shivamerla, we are no longer returning the Networks and Initiators objects as part of the Host object
* Networks and Initiators endpoints are already available to enumerate this information
* Reduces the overhead of enumerating basic host information such as the host ID, host name, and host domain
* driver.go
* Updated GetHostInfo() to not return the networks object (already wasn't returning the initiators)
* host_windows.go
* Added error logging if net.Interfaces() fails
* If windows.ERROR_NO_DATA is returned from the GetAdaptersInfo() Win32 API, we now return an empty NIC array with no error.  Windows maps ERROR_NO_DATA to "The pipe is being closed" which is a …

chapi2: Miscellaneous enhancements

---

Makefile

* Problem:
* "go install" is not necessary after a "go get"
* "go help get" specifically states that "Get downloads the packages named by the import paths, along with their dependencies. It then installs the named packages, like 'go install'"
* Removed any redundant "go install" entries
* Testing:
* Verified that "go get" compiles and installs the package locally
* Bug: N/A

Makefile: remove redundant install

---

dockerplugin/handler/mount.go
dockerplugin/provider/nimble_provider.go
model/types.go
tunelinux/iscsi.go

* Problem:
* inUse flag was not added for cloud volumes to handle fencing
* mountConflictDelay is not passed for cloud volumes
* current node initiator IP addresses were not filtered at plugin itself
* iscsi nr_sessions=4 was not being set for cloud
* added inUse response for volume properties if initiator is connected
* added initiator IP as response for iSCSI sessions instead of IQN name for cloud
* filter initiator IP list from user to include only current node IP's.
* add support for user to specify either IP addresses or interface names like eth0/eth1 etc to auto scale nodes.
* Testing:
tesed on EKS, with provisioning, node drain and pod delete.
* Review:
* Bug:

dockerplugin: fixes for cloud volume support

---

glide.lock
glide.yaml

* Problem:
* golang.org/x/crypto/ssh/terminal update causes build failures due to golang.org/x/sys being pinned to v1 tag.
* Change golang.org/x/crypto/ssh/terminal revision from "master" to the prior successful build, revision 227b76d455e791cb042b03e633e2f7fbcfdf74a5.
* Testing:
* Verified previous failed build will now build locally without error
* Reviewers:
* @shivamerla @suneeth51 @raunakkumar @rgcostea, @vidhutsingh 
* Bug: N/A

yaml:  Pin golang.org/x/crypto/ssh/terminal

---

linux/mount.go

* Problem:
* When fsType is not provided in storageClass(valid for cloning), external provisioner
* defaults to ext4. During nodeStage, if the cloned volume has fsType other than ext4, we
* are erroring out and failing stage.
* During fs creation we validate the type. But if FS is already present, we can safely assume its either
* a clone request or duplicate stage request. fsType mismatch can be ignored given that external provisioner
* passes a defaultType in all cases if not specified in storageClass. Other option is to fetch correct fsType
* from parent PVC/SC, but given we have cloneOf, DataSource, Snapshot types, that might not be necessary to put these
* checks into all types in controller-plugin.
* Testing: manual test with no fsType specified in SC.
* Review: …

csi/chapi: don't error out on fs mismatch if fs is already created

---

connectivity/client.go
storageprovider/csp/container_storage_provider.go

- The caller should pass the double pointer of error response structure so that the decoded error response is propagated back to the caller.
- Added more debug logs for tracking.

Fixed the error propogation issue

---

linux/mount.go

retries in that case and mount with no-uuid option directly

While mounting snapshots, XFS fails with duplicate FS UUID, avoid

---

dockerplugin/dockerplugin_windows.go
dockerplugin/plugin/plugin_windows.go

Bug DW-84 - Docker volumes created in other hosts are listed twice during volume list
Fix : 
Windows plugin listens on two ports which is a deviation from the Linux plugin where it listen on a single socket, it causes an issue with a windows plugin where the global volume started listing twice, one for local and one for global nimble driver. Modified the _windows.go code to listen only on single port.

Windows plugin listens on two ports which is not in parity with linux. Fixed it

---

linux/iscsi.go

* Problem:
* If the target is not reachable from some interfaces, then iscsi login will
* take long time 120s before timeout. This causes long delay during device
* discovery
* Add simple ping test before iSCSI login. Currently this is added only if iscsi interfaces
* are defined(cloud).
* Testing: Tested mount with multiple volumes on ec2 instance
* Review: gcostea, rkumar, sbyadarahalli

chapi: Add ping test before iscsi login to avoid timeout errors

---

model/types.go

Signed-off-by: vidhut-kumar-singh <vidhut-kumar.singh@hpe.com>
processMountConflictDealy is always timeouts since the IscsiSession and FCsession uses incorrect tag .

Fixed IscsiSession and FCSession tag for initiators and wwpn

---

linux/os.go

If kubelet is running in container, then FileOrCreate can create a directory if not present on host. Thus system files like /etc/redhat-release can appear as directory on Ubuntu host when mounted. Add directory checks to ignore parsing os info from them.

Workaround RKE issue where missing system files can appear as directories

---

dockerplugin/handler/mount.go
model/types.go

* Problem:
* Fiji rest-sdk reported iscsi/fc sessions using camelCase, while goa one reported
* with snake_case, thus unmarhalling fails from dockerplugin.
* Add legacy attributes for iscsi/fc sessions to handle both versions.
* Testing:
* Review:gcostea, vsingh

dockerplugin: fix issue with reporting of iscsi/fc session info between fiji/goa

---

chapi/chapidriver.go
chapi/chapidriver_darwin.go
chapi/chapidriver_fake.go
chapi/chapidriver_linux.go

* Problem:
* CSI driver is calling unmount call during nodeUnstage which does flush buffers as well
* flush buffers can hang as there is base mount still present
* Add handler to just perform unmount of bind mount path, but no sync
* Testing:
* Review: gcostea, rkumar, sbyadarahalli

chapi: Add bind unmount handler

---

linux/iscsi.go

Don't check for /dev/disk/by-path entries for VST targets and always
attempt login. Since the re-login attempt is more common with GST, we can
use those entries for lookup. This will avoid stale entry problem with
large number of targets repeatedly created/deleted.

Avoid checking /dev/disk/by-path entries for VST targets

---

tunelinux/iscsi.go

* Bug: https://github.com/hpe-storage/common-host-libs/issues/71

Fix order of iscsi settings to happen before service restart

---

linux/device.go
linux/iscsi.go
linux/iscsi_test.go
linux/multipath.go
linux/partition.go

* Problem:
* simultaneous calls to iscsiadm/multipathd were causing them to fail with timeout etc.
* getPartitions() was failing with error "not a block device" if called soon after device creation
* logging cleanup
* synchronize calls to iscsiadm/multipathd
* retry on failure to get partitions as multipath device setup takes few seconds
* logging cleanup
* Testing: tested with 50 pods on Ubuntu 16.04 and CentOS 7.6. rate of multipathd/iscsid failures have drastically reduced.
* Review:gcostea, rkumar

chapi: synchronize exec calls to iscsiadm/multipathd, misc fixes

---

chapi/chapidriver.go
chapi/chapidriver_darwin.go
chapi/chapidriver_fake.go
chapi/chapidriver_linux.go
linux/device.go
linux/multipath.go
tunelinux/config/config.json

* Problem:
* Need GetDevice() endpoint for csi driver to fetch current device from serial.
* Remove code which checks for Nimble device pattern.
* During device discovery don't agressively poll multipathd(i.e every second).
* During deletion request, check if device is mounted as first thing to avoid unnecessary retries.
* ISCSI queue_depth of 64 is very low for loaded system and TUR commands are taking ~16s to complete. This is the reason
* for multipathd timeouts.
* Added GetDevice() endpoint for csi driver to fetch existing device by serial.
* During device discovery changed polling interval to 5s, if we can't find multipath device after rescan. Thus
* multipathd can process pending commands quickly
* During deletion request, if device is mounted, error out …

chapi: miscellaneous fixes for scale issues

---

chapi/chapiclient.go
chapi/chapidriver.go
chapi/chapidriver_fake.go
chapi/chapidriver_linux.go
chapi/handler_linux.go
dockerplugin/handler/handler.go
dockerplugin/handler/host_handler.go
dockerplugin/handler/mount.go
linux/device.go
linux/iscsi.go
linux/network.go
model/types.go
tunelinux/iscsi.go

* Problem:
- support for cidr networks
- also support for multiple ip addresses on same interface https://github.com/hpe-storage/common-host-libs/issues/77
- support multiple discovery ips
to minimize the impact to existing chapi,flexvolume introduce new fields for CSI specific
* Testing:
tested with multiple interfaces and interface with multiple ips
* Bug: https://nimblejira.nimblestorage.com/browse/CON-568

chapi : support for cidr networks

---

chapi/chapidriver_linux.go
linux/mount.go
model/types.go
model/types_test.go

**Goal**
- Allow the user to pass command line options for use during filesystem creation.
- Options shall be opaque to this process
- Options not validated
- Options are limited to ```[a-zA-Z0-9=, \-]``` 
**Considerations:**
- There are a bunch of functions in the call stack to create a filesystem that are publicly scoped
- I maintained the public function signatures in case another application is using one of these
- The new functions can handle a nil for the options slice ([]string), so either should be safe
- The CHAPI interface leverages model.FilesystemOpts, which makes easy to sneak in the create options
**What I did:**
- Added a string to FilesystemOpts to capture create command line parameters (model)
- Added a function GetCreateOpts() to safely break the string into an array of …

Validating Approach for Filesystem Create Options

---

chapi/chapiclient.go
chapi/chapiclient_linux.go
chapi/chapiclient_windows.go
chapi/chapidriver_linux.go
chapi/handler_linux.go
dockerplugin/handler/get.go
dockerplugin/handler/mount.go
dockerplugin/handler/path.go
dockerplugin/plugin/plugin_linux.go
dockerplugin/plugin/plugin_windows.go
linux/device.go
linux/iscsi.go
linux/mount.go
linux/multipath.go
tunelinux/config.go
tunelinux/config/multipath.conf.generic
tunelinux/config/multipath.conf.upstream
tunelinux/disk.go
tunelinux/iscsi.go

* Problem:
* serial_number provided to chapi is assumed to be with scsi-id type prefix 2 (mpath)
* iscsi targets are looked up by nimble specific patterns and device filtering used nimble vendor types
* dependency on /dev/disk/by-path symlinks for logged-in sessions, but group wide targets might be logged-in
* without devices
* change to always assume serial number input to chapi is of volume serial number and same with returned types
* only consider scsi-id type prefix during mpath comparisions, not store anywhere
* add table for vendor patterns for device and target-iqn comparision and filtering
* fix function names to be generic
* Testing: in-progress with CSI/FlexVolume drivers
* Review: gcostea, rkumar, sbyadarahalli
* Bug: …

chapi: fix misc issues and support other vendors

---

chapi/chapidriver_linux.go
linux/bmount.go
linux/mount.go
linux/multipath.go

* Problem:
* When using chroot mechanism, both /var/lib/kubelet and /host will be mounted within container
* This will cause duplicate mount entries in /proc/mounts leading confusion in mount cleanup.
* Also, dmsetup remove is hanging within chroot.
* Use "mount" call to fetch mount points rather than /proc/mounts as its inconsistent. mount call always
* yeilds without duplicates.
* use multipathd remove instead of dmsetup remove to avoid hang issue.
* Testing: regression tests on RHEL 7.6, and pending on Ubuntu 16 and 18.

chapi: avoid /proc/mounts due to duplicates

---

linux/device.go

* Problem:
* Currently we use "multipathd reconfigure" after device resize.
* this causes all multipath tables to be reloaded causing delay
* and sometimes doesn't complete before fsResize is called.
* Also, "reconfigure" is async, so cannot guarantee table load
* is complete before we return the  call.
* Reload specific device which was asked to expand.
* Testing: tested on Ubuntu 18.04 and CentOS 7.5 with both block and fs expand.

linux: reload specific mpath on device resize

---

linux/device.go

multipathd reload doesn't update size of the map, use resize instead and error out on timeout errors.

---

storageprovider/csp/container_storage_provider.go
storageprovider/fake/fake_storage_provider.go
storageprovider/fake/fake_storage_provider_test.go
storageprovider/storage_provider.go

* Problem:
* Need api to edit volume properties to invoke CSP update volume.
* Added client api to invoke edit_volume with requested properties
* Testing: tested with volume-mutator

storageprovider: Add support to edit volume properties

---

glide.lock
glide.yaml

Testing:
```
glide get github.com/fsnotify/fsnotify#^v1.4.9
make packages
```

glide: add fsnotify dependency

---

chapi/chapidriver.go
chapi/chapidriver_darwin.go
chapi/chapidriver_fake.go
chapi/chapidriver_linux.go
linux/mount.go

* Problem:
* need capability in chapi to perform nfs mounts
* add endpoint which performs just mount without device checking.
* Testing: tested with nfs volumes using csi driver.

chapi: add nfs mount endpoint

---

linux/os.go

* Problem:
* Installing on Fedora yields empty service name for iscsi
* Drop iscsi map lookup for service names(legacy) as iscsi service
* name is now same across all major distros. Earlier it used to be
* open-iscsi on some SLES versions.
* Testing:

tunelinux: use constant iscsid service name across all distros

---

chapi/chapidriver.go
chapi/chapidriver_fake.go
chapi/chapidriver_linux.go
linux/mount.go

* Problem:
* Some flavors default to nfs4 and others to nfs4.1 causing mounts to fail if
* server doesn't support 4.1
* Add nfsType option to mount
* Testing: tested with multiple nfs mounts using csi
* Review: gcostea, rkumar, sbyadarahalli

chapi: provide option to specify nfs version type

---

logger/logger.go

* Problem:
* Windows Notepad, prior to Server 2019, does not display log files properly if they only end with LF
* Notepad is the default .log viewer for Windows
* Modified the logger.Fire() routine to add a custom check for Windows only
* The logrus Format() handler ends the line with just a LF
* The additional code scans for any trailing LF (excluding trailing CRLF) and replaces it with CRLF
* Testing:
* Verified log file viewable under windows
* Reviewers:
* @shivamerla, @raunakkumar 
* Bug: SV-764

logger:  Windows Notepad requires CRLF and not just LF

---

linux/iscsi.go

- chap user and password were only updated for a single target/portal.
- update chap user/password for all the target/portals matching the targetIqn

chapi: update chap credentials for all targets

---

chapi/chapidriver_linux.go
chapi/handler_linux.go
linux/device.go
linux/fc.go
linux/iscsi.go
linux/mount.go
model/types.go
tunelinux/config.go
tunelinux/disk.go
util/strings.go
util/volume.go

- Current in 3PAR/Primera CSP we are adding requirement for Peer persistence based Replication, where we need to create host and vlun's for both the Primary (source) array and the Target (secondary) array, so that the multipath device mapping will have paths from active/passive arrays. But, the publish volume response from CSP to CSI has currently support for only returning a single lun id. The change here is to return a object called SecondaryArrayDetails which will have list of object PeerDetails which has lun id, discovery ip, target names etc. One PeerDetail will be created per secondary backend.
- Approach
Changes are done to find, if the multiple luns are passed based on the number of PeerDetails in SecondaryArrayDetails struct. iscsi login , scanning all takes care of reading this …

Accomodate scanning for multiple lun id

---

linux/iscsi.go

* Problem:
* Run() method of go-ping is closing channel already on completion
* of 5 ping responses and in cases of timeouts. With additional
* closure during onRecv() can cause panic if multiple ping requests
* are inflight.
* Remove additional channel closure in client code and let go-ping
* package handle it.
* Testing: Tested pod attach/detach on multiple nodes.

chapi: remove redundant call to close pinger channel on responses.

---

linux/multipath.go

* Problem:
* Due to current regex, only devices with single digit host numbers in (H:C:T:L) are
* filtered to detect orphan paths. This is causing delay in device attach when
* paths are kept in orphan state by multipathd.
* Fix the regex to consider space before H:C:T:L numbers, so SCSI host numbers like
* 10, 11 etc are detected as well.
* Testing: Tested on scale setup to ensure orphan paths are detected correctly to speed up discovery.
* Review: gcostea, sbyadarahalli, rkumar

common-host-libs: Regex to detect orphan paths using single digit SCSI host number in H:C:T:L format

---

model/types.go

Collect volume stats from csp which CSI will use to return when NodeGetVolumeStats is invoked

CON-1072 : Make volume stats available for csi driver

---

linux/device.go
linux/iscsi.go
linux/multipath.go
model/types.go
tunelinux/filesystem.go

Problem statement:
There was an issue with iscsiadm logout step as part of the cleanup of deletedevices in NodeUnstageVolume. It deletes and logs out only 1 target node.
As part of nodeStageVolume, CSI creates deviceInfo.json and writes staging device information in it. But, it writes only one iscsiTarget info in it rather than a list
The mentioned PR has the fix for the multiple iscsi session logout.
It now writes the list of the iscsiTargets in deviceInfo.json file so that it logs out all the iscsi session.

Modified files for handling multiple iscsi session logout

---

linux/device.go

assign the iscsiTargets to device.IscsiTargets

device: do not dereference device.IscsiTargets[0]

---

linux/multipath.go
tunelinux/config/multipath.conf.generic
tunelinux/config/multipath.conf.upstream

This PR adds Device support for FreeNAS. It is a pre-req for [truenas-csp](https://github.com/hpe-storage/truenas-csp/issues/5) compatibility.

Adding FreeNAS support

---

logger/logger.go

Publish context map, which now contains sensitive encryption pass-phrase, was being logged in node_server:stageVolume() function. This PR would help scrub it before writing the map to log.
This is a pending change in the last PR on which csi-driver's PR https://github.com/hpe-storage/csi-driver/pull/246 is dependent on.
@raunakkumar - request you to review it following which I'll update the go.mod in csi-driver PR.

Enable scrubbing of sensitive information present in map

---

chapi/chapidriver_linux.go
util/strings.go
util/strings_test.go

Problem:
As seen in issue https://github.com/hpe-storage/csi-driver/issues/270
Two hosts have same mac addresses and although their hostnames differ,
we generate the same uuid as the mechanism to generate uuid does not guarantee
uniqueness.
Update the mechanism to pass it through md5 has to guarantee uniqueness for 32 characters

chapi: generate unique uuid for 2 hosts with same mac address

---

linux/mount.go

Problem:
- just like regular pvc mounts, if the mounts for the volume already exist(
the previous command times out or other reasons) we treat the subsequent mount as success if the same
source and target are present. The same logic was missing for nfs mounts.

chapi: busy or already mounted nfs mounts should be successfull

---

tunelinux/config/multipath.conf.generic
tunelinux/config/multipath.conf.upstream

Setting the hardware_handler to "1 alua" breaks for TrueNAS SCALE:
```
Oct 30 12:36:14 grisvakt-cpu3 kernel: sd 8:0:0:0: [sdb] Attached SCSI disk
Oct 30 12:36:15 grisvakt-cpu3 multipathd: sdb: add path (uevent)
Oct 30 12:36:15 grisvakt-cpu3 kernel: sd 7:0:0:0: alua: not supported
Oct 30 12:36:15 grisvakt-cpu3 kernel: sd 7:0:0:0: alua: not attached
Oct 30 12:36:15 grisvakt-cpu3 kernel: device-mapper: table: 252:0: multipath: error attaching hardware handler
Oct 30 12:36:15 grisvakt-cpu3 kernel: device-mapper: ioctl: error adding target to table
Oct 30 12:36:15 grisvakt-cpu3 multipathd: mpatha: failed in domap for addition of new path sdb
Oct 30 12:36:15 grisvakt-cpu3 multipathd: uevent trigger error
```
Removing the multipath.conf entry and it attaches fine.
```
Oct 30 12:41:08 …
```

Support TrueNAS SCALE

---

linux/device.go

@Pavan, @raunakkumar Please review
Fix for https://nimblejira.nimblestorage.com/browse/ESC-8915  
Resize for encrypted volumes on Redhat-8 is failing since the LUKS type is LUKS2 and key location: keyring which requires the passphrase.
Currently there is no option to pass the passphrase to stage volume.
If we format the device with LUKS1 instead LUKS2 the key location will be always dm-crypt .
[root@c3-sy480g10-20 ~]# cryptsetup status -v /dev/mapper/enc-mpathbcw
/dev/mapper/enc-mpathbcw is active and is in use.
**type:    LUKS1**
cipher:  aes-xts-plain64
keysize: 512 bits
**key location: dm-crypt**
device:  /dev/mapper/mpathbcw
sector size:  512
offset:  32768 sectors
size:    39813120 sectors
mode:    read/write
Command successful.

Formatting device with luks1 always

---

chapi/chapidriver_linux.go
model/types.go
tunelinux/multipath.go

The following functionalities are implemented in phase 3:
1. Unmount all references to the device, bind mounts, and real mounts.
2. Kill processes using the mount points and devices
3. Remove block devices
4. Flush the multipath map
made improvements for the previous  phase's implementation as well

CON2508: Handling the Cleanup  of stale multipath devices

---

tunelinux/config/config.json

- This fixes prevention of the CSI driver from starting as multipath commands writes non-parseable content on stderr for modern Linux distributions.

Legacy fixes

---

chapi/chapidriver_fake.go

Built with go version go1.23.1 and golangci-lint version 1.61.0 built with go1.23.1

Fixes for linter issues seen in csi-driver build using latest linter
