hpe-storage/common-host-libs

model/types.go, storageprovider/csp/container_storage_provider.go, storageprovider/csp/container_storage_provider_test.go, storageprovider/storage_provider.go
Changes to accept this header in the CSP are forthcoming in a separate review.
=> Update CSP headers

chapi/chapiclient.go
Earlier code merge didn't go through to master . So creating new pull request. 
Regression is introduced where it is expecting to have State field in device struct , windows chapi doesnt return thus leading to plugin crash on Windows while running mount command.
=> Win DVP crash during mount request 

chapi2/cerrors/cerrors.go, chapi2/cerrors/cerrors_windows.go, chapi2/iscsi/iscsi.go, chapi2/iscsi/iscsi_linux.go, chapi2/iscsi/iscsi_util.go, chapi2/iscsi/iscsi_windows.go, chapi2/model/types.go, chapi2/multipath/multipath.go, chapi2/multipath/multipath_windows.go, glide.lock, glide.yaml, windows/iscsidsc/login_iscsi_target.go
* Problem:
* Add CHAPI2 CreateDevice endpoint (for Windows)
* chapi2 model package
* Added const strings for ConnectTypeDefault, ConnectTypePing, ConnectTypeSubnet, and ConnectTypeAutoInitiator.  These are the supported iSCSI connection types.
* Added optional "ConnectType" property to "IscsiAccessInfo" object.
* chapi2 cerrors package
* Added Timeout and ConnectionFailed CHAPIErrorCode values
* Added a Windows specific IscsiErrToCerrors() function to convert a Win32 iSCSI error into cerrors.  Only converting commonly seen errors for now.
* chapi2 multipath package
* Added platform independent "AttachDevice" member function
* Replaced log.Info* routines with log.Trace* where applicable
* Changed "volume not found" with "device not found" to be consistent with other …
=> chapi2: Add CHAPI2 CreateDevice endpoint

chapi2/multipath/multipath_windows.go
* Problem:
* When onlining a cloned volume, and its parent volume is already mounted, you can experience a disk signature collision
* The cloned volume starts off online at the host.  If you try to online it using PowerShell, the online will fail and the volume becomes inaccessible
* You need to clear the volume's read only flag *before* you online the volume in order to allow the Windows resignature capability to engage
* Modified the MakeDiskOnlineAndWritable() routine to swap its ordering.  Now it will clear the read only flag before it tries to online the volume
* Testing:
* Used a Server 2019 host which had a GPT volume already mounted.  I then created a cloned volume, used CHAPI2 to attach the volume, and then used CHAPI2 to mount the volume to a specified mount …
=> multipath: Fix Windows mount clone failure

linux/iscsi.go
=> Fix typo in log message

linux/bmount.go
=> Make bind unmount idempotent

linux/device.go, linux/multipath.go
=> Fix declaration of err variable

storageprovider/csp/container_storage_provider.go
* Problem:
- allow login from one backend to happen only once
- Http error 200 gets logged during recursive invocation
of login
- have mutex per backend for login
- check for status code 200 and return immediately, have single variable
for status and error so that the values are not scope bound
* Testing:
* Bug: https://nimblejira.nimblestorage.com/browse/CON-573
=> storageprovider: misc fixes

chapi/chapidriver_linux.go, linux/mount.go, linux/mount_test.go, linux/os.go, model/types.go, model/types_test.go
The main thing to look at here is  linux/mount_test.go
A new test exercised the *WithOptions functions.  It take 18 seconds to run, but wont run unless mkfs.xfs is installed (which it isn't in most containers).
=> Somewhat duplicate PR, this time with test

.gitignore, model/types.go
Signed-off-by: Eric Forgette <eric.forgette@hpe.com>
=> Use better var names

linux/bmount.go
* Problem:
- during nodeUnpublish several threads
try to access /proc/mounts inside the container to retrive
the bind mounts. We've seen that there are inconsistent outputs
even for existing mounts
- take exclusive mutex lock for accessing /proc/mounts
* Testing:
* Bug: https://nimblejira.nimblestorage.com/browse/CON-597
=> serialize access of /proc/mounts

linux/iscsi.go, tunelinux/iscsi.go
=> Port logic of checking for logged-in iscsi sessions from master

linux/iscsi.go
Signed-off-by: Sneha Rai <sneha.rai@hpe.com>
=> Fix to perform discovery on all discoveryIPs returned by CSP

linux/iscsi.go
Signed-off-by: Sneha Rai <sneha.rai@hpe.com>
Co-authored-by: Sneha Rai <sneha.rai@hpe.com>
=> Fix to perform discovery on all discoveryIPs returned by CSP (#105)

logger/logger.go
* Problem:
* If a panic occurs while processing an HTTP request, the panic does not get recorded by the logger package
* Added a deferred routine to the logger.HTTPLogger function that detects a panic and records the stack trace to the error log
* Panic then continues through the defer process until http.serve() recovers it and closes the connection
* Testing:
* Tested with debug code that forced a panic to occur while processing a REST endpoint
* Reviewers:
* @shivamerla
* Bug: SV-691
=> logger: Add panic logging for http requests

storageprovider/fake/fake_storage_provider_test.go
=> Fix build with typo in function name for volume group creation test.

storageprovider/fake/fake_storage_provider_test.go
=> fix un-used variable.

storageprovider/fake/fake_storage_provider_test.go
=> Un-used variables cleanup

model/types.go, storageprovider/csp/container_storage_provider.go, storageprovider/fake/fake_storage_provider.go, storageprovider/fake/fake_storage_provider_test.go, storageprovider/storage_provider.go
=> support volumeGroup create/delete

util/watcher.go
We wanted to move the changes from https://github.com/hpe-storage/csi-driver/pull/145 PR to common-host-util as it is a generic mechanism. All the details are captured in the original PR .
=> Implemented generic os event driven mechanism

chapi/chapidriver_darwin.go
=> Fix function definition for darwin files

linux/network.go
* Problem:
* Current logic checks for all IPV4 addresses and perform reverse lookup.
* With container environments, they will include overlay network as well
* and incorrect host domains are obtained.
* Use dnsdomainname when available to obtain host domain name.
* Fallback to reverse lookup in other cases(very rare).
* Testing: tested chapi on both Ubuntu and RHEL hosts.
=> chapi: update logic to obtain host domain

model/types.go, storageprovider/csp/container_storage_provider.go, storageprovider/fake/fake_storage_provider.go, storageprovider/fake/fake_storage_provider_test.go, storageprovider/storage_provider.go
=> snapshotgroup: support for create/delete snapshot group

storageprovider/fake/fake_storage_provider.go, storageprovider/fake/fake_storage_provider_test.go
=> add missing definition to fake_storage_provider

storageprovider/csp/container_storage_provider.go
=> Allow edit of description via mutator

linux/iscsi.go, linux/multipath.go, tunelinux/config/multipath.conf.generic, tunelinux/config/multipath.conf.upstream
- Allow discovery of TrueNAS Core disks and targets.
- Added multipath.conf stanzas
=> Added support for TrueNAS Core CSP

storageprovider/csp/container_storage_provider.go
Ensure appropriate error messages are transferred from CSP to the CSI logs
=> CON-1071: Pass the error message from CSP to CSI when operator role is used

windows/advapi32/advapi32.go
* Add wrapper for Advapi32.dll SetSecurityInfo Win32 API
* API details:  https://docs.microsoft.com/en-us/windows/win32/api/aclapi/nf-aclapi-setsecurityinfo
* Testing:
* API tested when used with local POC code
* Reviewers:
* @raunakkumar @rgcostea 
* Bug: N/A
=> advapi32: Add wrapper for SetSecurityInfo Win32 API

linux/device.go, linux/mount.go, model/types.go, util/cmd.go
Volume encryption support is a host-based encryption using LUKS tool called cryptsetup. During node-stage flow, cryptsetup tool is used on the discovered device to enable encryption. For details about the approach please refer to https://rndwiki.corp.hpecorp.net/confluence/display/storageecosystem/Volume+encryption+support+in+CSI+Driver
@rgcostea , @raunakkumar , @wdurairaj , @sneharai4 - please review the changes
=> Volume encryption support

storageprovider/csp/container_storage_provider.go
Signed-off-by: Suneeth Kumar Byadara Halli <suneethkumar.byadarahalli@hpe.com>
=> Fixed the logs not to print sensitive header data

model/types.go
Signed-off-by: Suneeth Kumar Byadara Halli <suneethkumar.byadarahalli@hpe.com>
=> Add new PublishInfo attribute 'is_cloud' for CSP type flag

chapi/chapidriver.go, chapi/chapidriver_darwin.go, chapi/chapidriver_fake.go, chapi/chapidriver_linux.go, linux/device.go
=> chapidriver: add support to check block device and size

model/types.go
Signed-off-by: Suneeth Kumar Byadara Halli <suneethkumar.byadarahalli@hpe.com>
=> Removed IsCloud attribute

storageprovider/csp/container_storage_provider.go, storageprovider/storage_provider.go, storageprovider/storage_provider_test.go
Signed-off-by: Sneha Rai <sneha.rai@hpe.com>
=> Added csp client timeout to be configurable

linux/device.go, linux/multipath.go
This is proposed fix for issue : CIDG-1395:  CSI 2.0.0 - Scale - Statefulset - iscsci | 50 Pod deletion took more that 25 minutes
Testing is still in progress. 
Please review it: 
@sneharai4 
@bhagyashree-sarawate 
Signed-off-by: jyotsna-l <jyotsna.l@hpe.com>
=> CIDG-1395 : Changed the placement of logoutAndDeleteIscsiTarget() call

connectivity/client.go, dockerplugin/handler/create.go, dockerplugin/handler/mount.go, dockerplugin/handler/remove.go, dockerplugin/plugin/plugin.go, linux/device.go, logger/logger_test.go, logger/test.log, storageprovider/csp/container_storage_provider.go, storageprovider/csp/container_storage_provider_test.go, storageprovider/fake/fake_storage_provider_test.go
=> fix more linting errors

linux/device.go
@raunakkumar , pavan-s-shanbhag@hpe.com
Still testing is in progress. so keeping the extra log lines  ..but raising the PR to get any early feedback for the fix and discussion
=> WIP: Remaplun fix by reading the wwid instead the vpdpath in case of 3PAR

mpathconfig/configresource_test.go, mpathconfig/multipath_test.conf
Signed-off-by: Adarsh Pratik <adarsh.pratik@hpe.com>
=> Fixed test case failures for multipath.conf changes

linux/iscsi.go
Fixes: #173 
Signed-off-by: Tim Peoples <tim@toolman.org>
=> Add "org.freenas.ctl" to list of targetVendorPatterns

util/cmd.go
Signed-off-by: sijeesh <sijeesh.kattumunda@hpe.com>
=> ExecCommandOutputWithTimeout-timeout parameter fix

linux/iscsi.go, linux/multipath.go
Fixes for detaching volume scoped targets (VST) for iSCSI.
- Enumerate each target
- Pass if targets nodes and sessions are missing
- Exits if mpath device is busy flushing caches from the umount
Previous behavior enumerated all connected targets and logged out all targets on first pass. Additional passes fail and delays detaching significantly (10 retries) and confuses the external attacher which lead to 5+ minutes long process for detaching a device and lingering iSCSI sessions.
Passes CSI e2e tests for HPE iSCSI GSTs (stock Nimble and 3PAR) and VSTs (old Nimbles and 3rd party).
=> Fix for iSCSI VSTs
